###**Name kyreen bhatia**
###**Class 9 kanha**

<img src="https://ik.imagekit.io/6ayejlpojhi/colab_images/numpy_hZeWwX5EjT.png?updatedAt=1692178594239" width=300/>

#**Numpy Exercise**
* 1D and 2D array slicing

###**Exercise 1: Create and slice and print alternate elements from a given numpy array.**
[11,12,13,14,15,16,17,18,19,20]

In [19]:
import numpy as np
array=np.arange(10,21,1)
print(array)
print(array[0:11:2])

[10 11 12 13 14 15 16 17 18 19 20]
[10 12 14 16 18 20]


###**Exercise 2: Slice and print the last three elements of a given numpy array.**
[11,12,13,14,15,16,17,18,19,20]

In [21]:
import numpy as np
array=np.arange(10,21,1)
print(array)
print(array[8:11:1])

[10 11 12 13 14 15 16 17 18 19 20]
[18 19 20]


###**Exercise 3: Slice and print elements from index 3 to index 7 (exclusive) from a given numpy array.**
[11,12,13,14,15,16,17,18,19,20]

Expected Output:
[14 15 16 17]


In [23]:
import numpy as np
array=np.arange(10,21,1)
print(array)
print(array[4:8:1])

[10 11 12 13 14 15 16 17 18 19 20]
[14 15 16 17]


###**Exercise 4: Slice and print elements in reverse order.**
Actual Array: [11,12,13,14,15,16,17,18,19,20]

Expected Output: [20,19,18,17,16,15,14,13,12,11]

In [24]:
import numpy as numpy
array=np.arange(10,21,1)
print(array)
print(array[11:0:-1])

[10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11]


###**Excercise 5: Create the following array**
<img src="https://ik.imagekit.io/6ayejlpojhi/colab_images/Screenshot%202024-03-07%20at%2012.05.20%20PM_M0p7A3WIFI.png?updatedAt=1709793190261"/>

In [28]:
import numpy as np
array=np.arange(5,130,5)
print(array)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125]


###**Excercise 6: Slice following array according to the image given below**

<img src="https://ik.imagekit.io/6ayejlpojhi/colab_images/Ex7_zpXAouXYl.png?updatedAt=1710221958007"/>

In [31]:
import numpy as np
array=np.arange(5,130,5)
print(array)
array=array.reshape(5,5)
print(array)
array[1:5,1:5]

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125]
[[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]
 [105 110 115 120 125]]


array([[ 35,  40,  45,  50],
       [ 60,  65,  70,  75],
       [ 85,  90,  95, 100],
       [110, 115, 120, 125]])

###**Excercise 7: Slice following array according to the image given below**

<img src="https://ik.imagekit.io/6ayejlpojhi/colab_images/Ex8_EkVyeFFdqN.png?updatedAt=1710221917482"/>

In [33]:
import numpy as np
array=np.arange(5,130,5)
print(array)
array=array.reshape(5,5)
array[1:4,1:4]

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125]


array([[35, 40, 45],
       [60, 65, 70],
       [85, 90, 95]])

###**Excercise 8: Slice following array according to the image given below (Bonus Question)**

<img src="https://ik.imagekit.io/6ayejlpojhi/colab_images/Ex6_HTiIFnN9JR.png?updatedAt=1710221917387"/>

In [ ]:
#Kindly write your code here